DROP TABLE CLASS_TBL;
DROP TABLE CLASS2_TBL;
DROP TABLE STUDENT_TBL;



CREATE TABLE STUDENT_TBL (
    STUDENT_NO VARCHAR2(5 BYTE) NOT NULL,
    STUDENT_NAME VARCHAR2(15 BYTE) NULL,
    STUDENT_AGE NUMBER(3)         NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NO)
);

CREATE TABLE CLASS2_TBL (
    CLASS_CODE VARCHAR2(1 BYTE)  NOT NULL,
    CLASS_NAME VARCHAR2(10 BYTE) NULL,
    CLASS_TC VARCHAR2(15 BYTE) NULL,
    CONSTRAINT PK_CLASS2 PRIMARY KEY(CLASS_CODE)
);

CREATE TABLE CLASS_TBL (
    CLASS_NO NUMBER NOT NULL,
    STUDENT_NO VARCHAR2(5 BYTE) NOT NULL,
    CLASS_CODE VARCHAR2(1 BYTE) NOT NULL,
    CONSTRAINT PK_CLASS PRIMARY KEY(CLASS_NO),
    CONSTRAINT FK_CLASS_STUDENT FOREIGN KEY(STUDENT_NO) REFERENCES STUDENT_TBL(STUDENT_NO),
    CONSTRAINT FK_CLASS_CLASS2 FOREIGN KEY(CLASS_CODE) REFERENCES CLASS2_TBL(CLASS_CODE)
);